package view.inferna_frame;

import model.Empresa;
import controller.ContasPagarReceberCtr;
import model.alterado.ContasFornecedoresJComboBox;
import model.alterado.UsuariosJComboBox;

/**
 *
 * @author RODOLFO
 */
public class JIFContasPagarReceber extends javax.swing.JInternalFrame {

    public static Empresa empresa;
    private ContasPagarReceberCtr controller;

    /**
     * Creates new form JIFContasPagarReceber
     */
    public JIFContasPagarReceber() {
        initComponents();
        this.controller = new ContasPagarReceberCtr();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbFornecedorPesquisa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcbContasPesquisa = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tbxDescricaoPesquisa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbTipoContaPesquisa = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcbStatusContaPesquisa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcbTipoDataPesquisa = new javax.swing.JComboBox<>();
        jcDataFinal = new com.toedter.calendar.JCalendar();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcDataInicial = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnPesquisaPesquisa = new javax.swing.JButton();
        btnLimparPesquisa = new javax.swing.JButton();
        btnOutrosMeses = new javax.swing.JToggleButton();
        btnBaixarContaPesquisa = new javax.swing.JButton();
        btnBotaoEditarContaPesquisa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNovoSalvar = new javax.swing.JButton();
        btnSalvarCadastro = new javax.swing.JButton();
        btnAdicionarRecorrencia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jcbFornecedorCadastro = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jcbContaFornecedorCadastro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tbxDescricaoCadastro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tbxValorContaCadastro = new javax.swing.JFormattedTextField();
        tbxValorPagoCadastro = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tbxValorJuroDescontoCadastro = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jcbTipoJuroDescontoCadastro = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jcbTipoContaCadastro = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jcbStatusContaCadastro = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        tbxTransacaoCadastro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jcbBoletoCadastro = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jcbComprovanteCadastro = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jcDataCadastroCadastro = new com.toedter.calendar.JCalendar();
        jcDataVencimentoCadastro = new com.toedter.calendar.JCalendar();
        jcDataBaixaCadastro = new com.toedter.calendar.JCalendar();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCadastroContaRecorrente = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btnLimparBaixaContas = new javax.swing.JButton();
        btnPagarBaixaContas = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tbxCodigoContaBaixaContas = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tbxFornecedorBaixaContas = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tbxContaFornecedorBaixaContas = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tbxNomeContaBaixaContas = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbxDescricaoBaixaContas = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        tbxValorContaBaixaContas = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        tbxValorPagoBaixaContas = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        tbxValorJuroDescontoBaixaContas = new javax.swing.JFormattedTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        cbJuroDescontoBaixaContas = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        cbTipoContaBaixaContas = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        cbStatusContaBaixaContas = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        cbComprovanteBaixaContas = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        cbBoletoBaixaContas = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        tbxTransacaoBaixaContas = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jcDataCadastroBaixaContas = new com.toedter.calendar.JCalendar();
        jPanel13 = new javax.swing.JPanel();
        jcDataVencimentoBaixaContas = new com.toedter.calendar.JCalendar();
        jPanel14 = new javax.swing.JPanel();
        jcDataPagamentoBaixaContas = new com.toedter.calendar.JCalendar();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Contas Pagar Receber");

        jTabbedPane1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel1.setText("Fornecedor:");

        jcbFornecedorPesquisa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jcbFornecedorPesquisa.addItemListener(this::jcbFornecedorPesquisaItemStateChanged);
        jcbFornecedorPesquisa.addActionListener(this::jcbFornecedorPesquisaActionPerformed);

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel2.setText("Nome Conta:");

        jcbContasPesquisa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        tbxDescricaoPesquisa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel4.setText("Tipo Conta:");

        jcbTipoContaPesquisa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jcbTipoContaPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODAS", "PAGAR", "RECEBER" }));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel5.setText("Status Conta: ");

        jcbStatusContaPesquisa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jcbStatusContaPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODAS", "AGUARDANDO", "PAGO", "CANCELADO", "VENCIDA" }));

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel6.setText("Tipo de Data:");

        jcbTipoDataPesquisa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jcbTipoDataPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DATA VENCIMENTO", "DATA CADASTRO", "DATA BAIXA" }));

        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel7.setText("INÍCIO");

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel8.setText("FIM");

        tabela.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        btnPesquisaPesquisa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnPesquisaPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/pesquisa.png"))); // NOI18N
        btnPesquisaPesquisa.setText("PESQUISAR");
        btnPesquisaPesquisa.addActionListener(this::btnPesquisaPesquisaActionPerformed);

        btnLimparPesquisa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnLimparPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/new.png"))); // NOI18N
        btnLimparPesquisa.setText("LIMPAR FILTROS");

        btnOutrosMeses.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnOutrosMeses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/contas.png"))); // NOI18N
        btnOutrosMeses.setText("OUTROS MESES");
        btnOutrosMeses.setEnabled(false);
        btnOutrosMeses.addActionListener(this::btnOutrosMesesActionPerformed);

        btnBaixarContaPesquisa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnBaixarContaPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/marcar_pago.png"))); // NOI18N
        btnBaixarContaPesquisa.setText("BAIXAR CONTA");
        btnBaixarContaPesquisa.addActionListener(this::btnBaixarContaPesquisaActionPerformed);

        btnBotaoEditarContaPesquisa.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnBotaoEditarContaPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/moneyBack.png"))); // NOI18N
        btnBotaoEditarContaPesquisa.setText("EDITAR CONTA");
        btnBotaoEditarContaPesquisa.addActionListener(this::btnBotaoEditarContaPesquisaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbFornecedorPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbContasPesquisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxDescricaoPesquisa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTipoContaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbStatusContaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(jcbTipoDataPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimparPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisaPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOutrosMeses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBaixarContaPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBotaoEditarContaPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1445, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcbFornecedorPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jcbContasPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tbxDescricaoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jcbTipoContaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jcbStatusContaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jcbTipoDataPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jcDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jcDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLimparPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOutrosMeses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBaixarContaPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBotaoEditarContaPesquisa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PESQUISA CONTAS", jPanel1);

        jToolBar1.setRollover(true);

        btnNovoSalvar.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnNovoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/new.png"))); // NOI18N
        btnNovoSalvar.setText("NOVO");
        btnNovoSalvar.setFocusable(false);
        btnNovoSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovoSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNovoSalvar);

        btnSalvarCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnSalvarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/salvar.png"))); // NOI18N
        btnSalvarCadastro.setText("SALVAR");
        btnSalvarCadastro.setEnabled(false);
        btnSalvarCadastro.setFocusable(false);
        btnSalvarCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvarCadastro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvarCadastro.addActionListener(this::btnSalvarCadastroActionPerformed);
        jToolBar1.add(btnSalvarCadastro);

        btnAdicionarRecorrencia.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnAdicionarRecorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/calendario_relogio.png"))); // NOI18N
        btnAdicionarRecorrencia.setText("CONTA RECORRENTE");
        btnAdicionarRecorrencia.setFocusable(false);
        btnAdicionarRecorrencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarRecorrencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionarRecorrencia.addActionListener(this::btnAdicionarRecorrenciaActionPerformed);
        jToolBar1.add(btnAdicionarRecorrencia);

        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel9.setText("FORNECEDOR:");

        jcbFornecedorCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jcbFornecedorCadastro.addActionListener(this::jcbFornecedorCadastroActionPerformed);

        jLabel10.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel10.setText("CONTA FORNECEDOR:");

        jcbContaFornecedorCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel11.setText("DESCRIÇÃO:");

        tbxDescricaoCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel12.setText("VALOR CONTA:");

        tbxValorContaCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tbxValorContaCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        tbxValorPagoCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tbxValorPagoCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel13.setText("VALOR PAGO:");

        jLabel14.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel14.setText("VALOR JURO/DESCONTO:");

        tbxValorJuroDescontoCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tbxValorJuroDescontoCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel15.setText("TIPO JURO/DESCONTO:");

        jcbTipoJuroDescontoCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jcbTipoJuroDescontoCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "JURO", "DESCONTO" }));

        jLabel16.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel16.setText("TIPO CONTA:");

        jcbTipoContaCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jcbTipoContaCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAGAR", "RECEBER" }));

        jLabel17.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel17.setText("STATUS CONTA:");

        jcbStatusContaCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jcbStatusContaCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGUARDANDO", "PAGA", "VENCIDA", "CANCELADA" }));

        jLabel18.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel18.setText("TRANSAÇÃO:");

        tbxTransacaoCadastro.setEditable(false);
        tbxTransacaoCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel19.setText("BOLETO:");

        jcbBoletoCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jcbBoletoCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAO", "SIM" }));
        jcbBoletoCadastro.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel20.setText("COMRPOVANTE:");

        jcbComprovanteCadastro.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jcbComprovanteCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAO", "SIM" }));
        jcbComprovanteCadastro.setEnabled(false);

        jcDataCadastroCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA CADASTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        jcDataVencimentoCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA VENCIMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        jcDataBaixaCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA BAIXA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jcDataCadastroCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcDataVencimentoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jcDataBaixaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcDataCadastroCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcDataVencimentoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcDataBaixaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbxDescricaoCadastro)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbFornecedorCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbContaFornecedorCadastro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbTipoJuroDescontoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbTipoContaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbStatusContaCadastro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbxValorContaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbxValorPagoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbxValorJuroDescontoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbxTransacaoCadastro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbBoletoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbComprovanteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(179, 179, 179)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcbFornecedorCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jcbContaFornecedorCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxDescricaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tbxValorContaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tbxValorPagoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tbxValorJuroDescontoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jcbTipoJuroDescontoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jcbTipoContaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jcbStatusContaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tbxTransacaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jcbBoletoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jcbComprovanteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabelaCadastroContaRecorrente.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tabelaCadastroContaRecorrente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabelaCadastroContaRecorrente);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 285, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("CADASTRO E EDIÇÃO DE CONTAS", jPanel3);

        jPanel6.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jToolBar2.setRollover(true);

        btnLimparBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnLimparBaixaContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/new.png"))); // NOI18N
        btnLimparBaixaContas.setText("LIMPAR");
        btnLimparBaixaContas.setFocusable(false);
        btnLimparBaixaContas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparBaixaContas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparBaixaContas.addActionListener(this::btnLimparBaixaContasActionPerformed);
        jToolBar2.add(btnLimparBaixaContas);

        btnPagarBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnPagarBaixaContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/pay.png"))); // NOI18N
        btnPagarBaixaContas.setText("SALVAR");
        btnPagarBaixaContas.setEnabled(false);
        btnPagarBaixaContas.setFocusable(false);
        btnPagarBaixaContas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagarBaixaContas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnPagarBaixaContas);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CÓDIGOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        jLabel21.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel21.setText("CÓDIGO CONTA");

        tbxCodigoContaBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tbxCodigoContaBaixaContas.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel22.setText("FONECEDOR");

        tbxFornecedorBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tbxFornecedorBaixaContas.setEnabled(false);

        jLabel23.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel23.setText("CONTA FORNECEDOR");

        tbxContaFornecedorBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tbxContaFornecedorBaixaContas.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbxFornecedorBaixaContas)
                            .addComponent(tbxCodigoContaBaixaContas)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxContaFornecedorBaixaContas)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tbxCodigoContaBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tbxFornecedorBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tbxContaFornecedorBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS CONTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        jLabel24.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel24.setText("NOME CONTA");

        tbxNomeContaBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tbxNomeContaBaixaContas.setEnabled(false);

        jLabel25.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel25.setText("DESCRIÇÃO");

        tbxDescricaoBaixaContas.setColumns(20);
        tbxDescricaoBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tbxDescricaoBaixaContas.setRows(5);
        tbxDescricaoBaixaContas.setEnabled(false);
        jScrollPane3.setViewportView(tbxDescricaoBaixaContas);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxNomeContaBaixaContas))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tbxNomeContaBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VALORES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        jLabel26.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel26.setText("VALOR CONTA");

        tbxValorContaBaixaContas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tbxValorContaBaixaContas.setEnabled(false);
        tbxValorContaBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel27.setText("VALOR PAGO");

        tbxValorPagoBaixaContas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        tbxValorPagoBaixaContas.setEnabled(false);
        tbxValorPagoBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel28.setText("VALOR JURO/DESCONTO");

        tbxValorJuroDescontoBaixaContas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tbxValorJuroDescontoBaixaContas.setEnabled(false);
        tbxValorJuroDescontoBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxValorContaBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxValorPagoBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxValorJuroDescontoBaixaContas)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tbxValorContaBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(tbxValorPagoBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(tbxValorJuroDescontoBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS CONTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        jLabel29.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel29.setText("JURO/DESCONTO");

        cbJuroDescontoBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        cbJuroDescontoBaixaContas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "JURO", "DESCONTO" }));
        cbJuroDescontoBaixaContas.setEnabled(false);

        jLabel30.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel30.setText("TIPO CONTA");

        cbTipoContaBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        cbTipoContaBaixaContas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAGAR", "RECEBER" }));
        cbTipoContaBaixaContas.setEnabled(false);

        jLabel31.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel31.setText("STATUS CONTA");

        cbStatusContaBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        cbStatusContaBaixaContas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGUARDANDO", "PAGO", "CANCELADO", "VENCIDA" }));
        cbStatusContaBaixaContas.setEnabled(false);

        jLabel32.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel32.setText("COMPROVANTE");

        cbComprovanteBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        cbComprovanteBaixaContas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAO", "SIM" }));
        cbComprovanteBaixaContas.setEnabled(false);

        jLabel33.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel33.setText("BOLETO");

        cbBoletoBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        cbBoletoBaixaContas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAO", "SIM" }));
        cbBoletoBaixaContas.setEnabled(false);

        jLabel34.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel34.setText("TRANSAÇÃO");

        tbxTransacaoBaixaContas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tbxTransacaoBaixaContas.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbJuroDescontoBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbComprovanteBaixaContas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipoContaBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBoletoBaixaContas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxTransacaoBaixaContas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStatusContaBaixaContas, 0, 139, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cbJuroDescontoBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(cbTipoContaBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(cbStatusContaBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cbComprovanteBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(cbBoletoBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tbxTransacaoBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA CADASTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        jcDataCadastroBaixaContas.setEnabled(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcDataCadastroBaixaContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jcDataCadastroBaixaContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA VENCIMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        jcDataVencimentoBaixaContas.setEnabled(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcDataVencimentoBaixaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jcDataVencimentoBaixaContas, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA PAGAMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono", 0, 14))); // NOI18N

        jcDataPagamentoBaixaContas.setEnabled(false);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcDataPagamentoBaixaContas, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jcDataPagamentoBaixaContas, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(391, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BAIXA DE CONTAS", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaPesquisaActionPerformed
        this.controller.pesquisarDados();
    }//GEN-LAST:event_btnPesquisaPesquisaActionPerformed

    private void jcbFornecedorPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFornecedorPesquisaActionPerformed
        this.controller.PesquisarContaFornecedor(jcbFornecedorPesquisa, jcbContasPesquisa);
    }//GEN-LAST:event_jcbFornecedorPesquisaActionPerformed

    private void jcbFornecedorPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbFornecedorPesquisaItemStateChanged

    }//GEN-LAST:event_jcbFornecedorPesquisaItemStateChanged

    private void btnOutrosMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutrosMesesActionPerformed
        if (btnOutrosMeses.isSelected() == true) {
            this.controller.pesquisarTodasContasVencidas();
            btnPesquisaPesquisa.setEnabled(false);
        }else{
            btnPesquisaPesquisa.setEnabled(true);
            this.controller.PesquisarContaFornecedor(jcbFornecedorPesquisa, jcbContasPesquisa);
        }
    }//GEN-LAST:event_btnOutrosMesesActionPerformed

    private void jcbFornecedorCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFornecedorCadastroActionPerformed
        this.controller.PesquisarContaFornecedor(jcbFornecedorCadastro, jcbContaFornecedorCadastro);
    }//GEN-LAST:event_jcbFornecedorCadastroActionPerformed

    private void btnAdicionarRecorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarRecorrenciaActionPerformed
        this.controller.AdicionarContaRecorrenteTabela();
    }//GEN-LAST:event_btnAdicionarRecorrenciaActionPerformed

    private void btnSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroActionPerformed
        this.controller.validaCadastro();
    }//GEN-LAST:event_btnSalvarCadastroActionPerformed

    private void btnBotaoEditarContaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotaoEditarContaPesquisaActionPerformed
        this.controller.colocarDados();
    }//GEN-LAST:event_btnBotaoEditarContaPesquisaActionPerformed

    private void btnLimparBaixaContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparBaixaContasActionPerformed
        this.controller.LimparCampos(false);
    }//GEN-LAST:event_btnLimparBaixaContasActionPerformed

    private void btnBaixarContaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaixarContaPesquisaActionPerformed
        this.controller.selecionarDados();
    }//GEN-LAST:event_btnBaixarContaPesquisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdicionarRecorrencia;
    public static javax.swing.JButton btnBaixarContaPesquisa;
    public static javax.swing.JButton btnBotaoEditarContaPesquisa;
    public static javax.swing.JButton btnLimparBaixaContas;
    public static javax.swing.JButton btnLimparPesquisa;
    public static javax.swing.JButton btnNovoSalvar;
    public static javax.swing.JToggleButton btnOutrosMeses;
    public static javax.swing.JButton btnPagarBaixaContas;
    public static javax.swing.JButton btnPesquisaPesquisa;
    public static javax.swing.JButton btnSalvarCadastro;
    public static javax.swing.JComboBox<String> cbBoletoBaixaContas;
    public static javax.swing.JComboBox<String> cbComprovanteBaixaContas;
    public static javax.swing.JComboBox<String> cbJuroDescontoBaixaContas;
    public static javax.swing.JComboBox<String> cbStatusContaBaixaContas;
    public static javax.swing.JComboBox<String> cbTipoContaBaixaContas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    public static com.toedter.calendar.JCalendar jcDataBaixaCadastro;
    public static com.toedter.calendar.JCalendar jcDataCadastroBaixaContas;
    public static com.toedter.calendar.JCalendar jcDataCadastroCadastro;
    public static com.toedter.calendar.JCalendar jcDataFinal;
    public static com.toedter.calendar.JCalendar jcDataInicial;
    public static com.toedter.calendar.JCalendar jcDataPagamentoBaixaContas;
    public static com.toedter.calendar.JCalendar jcDataVencimentoBaixaContas;
    public static com.toedter.calendar.JCalendar jcDataVencimentoCadastro;
    public static javax.swing.JComboBox<String> jcbBoletoCadastro;
    public static javax.swing.JComboBox<String> jcbComprovanteCadastro;
    public static javax.swing.JComboBox<ContasFornecedoresJComboBox> jcbContaFornecedorCadastro;
    public static javax.swing.JComboBox<ContasFornecedoresJComboBox> jcbContasPesquisa;
    public static javax.swing.JComboBox<UsuariosJComboBox> jcbFornecedorCadastro;
    public static javax.swing.JComboBox<UsuariosJComboBox> jcbFornecedorPesquisa;
    public static javax.swing.JComboBox<String> jcbStatusContaCadastro;
    public static javax.swing.JComboBox<String> jcbStatusContaPesquisa;
    public static javax.swing.JComboBox<String> jcbTipoContaCadastro;
    public static javax.swing.JComboBox<String> jcbTipoContaPesquisa;
    public static javax.swing.JComboBox<String> jcbTipoDataPesquisa;
    public static javax.swing.JComboBox<String> jcbTipoJuroDescontoCadastro;
    public static javax.swing.JTable tabela;
    public static javax.swing.JTable tabelaCadastroContaRecorrente;
    public static javax.swing.JTextField tbxCodigoContaBaixaContas;
    public static javax.swing.JTextField tbxContaFornecedorBaixaContas;
    public static javax.swing.JTextArea tbxDescricaoBaixaContas;
    public static javax.swing.JTextField tbxDescricaoCadastro;
    public static javax.swing.JTextField tbxDescricaoPesquisa;
    public static javax.swing.JTextField tbxFornecedorBaixaContas;
    public static javax.swing.JTextField tbxNomeContaBaixaContas;
    public static javax.swing.JTextField tbxTransacaoBaixaContas;
    public static javax.swing.JTextField tbxTransacaoCadastro;
    public static javax.swing.JFormattedTextField tbxValorContaBaixaContas;
    public static javax.swing.JFormattedTextField tbxValorContaCadastro;
    public static javax.swing.JFormattedTextField tbxValorJuroDescontoBaixaContas;
    public static javax.swing.JFormattedTextField tbxValorJuroDescontoCadastro;
    public static javax.swing.JFormattedTextField tbxValorPagoBaixaContas;
    public static javax.swing.JFormattedTextField tbxValorPagoCadastro;
    // End of variables declaration//GEN-END:variables
public void LoadFormulario() {
        this.controller.LoadFormulario();
    }
}
