package view.inferna_frame;

import controller.ContaFornecedorCtr;
import model.Empresa;

/**
 * Formulário responsável por fazer o vinculo dos fornecedores as contas
 *
 * @author RODOLFO
 */
public class JIFContaFornecedor extends javax.swing.JInternalFrame {

    public static Empresa empresa;
    public ContaFornecedorCtr controller;
    public static boolean fornecedor_conta;

    /**
     * Creates new form JIFContaFornecedor
     */
    public JIFContaFornecedor() {
        initComponents();
        this.controller = new ContaFornecedorCtr();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesquisarFornecedor = new javax.swing.JButton();
        btnPesquisarContasVinculadas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbxIdConta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbxIDFornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tbxNomeFornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tbxNomeConta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbStatusConta = new javax.swing.JComboBox<>();
        jcDataCadastro = new com.toedter.calendar.JCalendar();
        jLabel6 = new javax.swing.JLabel();
        tbxDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Vincular Contas aos Fornecedores");

        jToolBar1.setRollover(true);

        btnNovo.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/new.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.setToolTipText("NOVO");
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        jToolBar1.add(btnNovo);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/salvar.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setToolTipText("SALVAR");
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        jToolBar1.add(btnSalvar);

        btnPesquisarFornecedor.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnPesquisarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/pesquisa.png"))); // NOI18N
        btnPesquisarFornecedor.setText("FORN.");
        btnPesquisarFornecedor.setToolTipText("PESQUISAR FORNECEDORES");
        btnPesquisarFornecedor.setFocusable(false);
        btnPesquisarFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisarFornecedor.addActionListener(this::btnPesquisarFornecedorActionPerformed);
        jToolBar1.add(btnPesquisarFornecedor);

        btnPesquisarContasVinculadas.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btnPesquisarContasVinculadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/pesquisa.png"))); // NOI18N
        btnPesquisarContasVinculadas.setText("CONTAS");
        btnPesquisarContasVinculadas.setToolTipText("PESQUISAR CONTAS");
        btnPesquisarContasVinculadas.setFocusable(false);
        btnPesquisarContasVinculadas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarContasVinculadas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisarContasVinculadas.addActionListener(this::btnPesquisarContasVinculadasActionPerformed);
        jToolBar1.add(btnPesquisarContasVinculadas);

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel1.setText("ID CONTA:");

        tbxIdConta.setEditable(false);
        tbxIdConta.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel2.setText("ID FORN.:");

        tbxIDFornecedor.setEditable(false);
        tbxIDFornecedor.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel3.setText("NOME FOR.:");

        tbxNomeFornecedor.setEditable(false);
        tbxNomeFornecedor.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tbxNomeFornecedor.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel4.setText("NOME CONTA:");

        tbxNomeConta.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel5.setText("STATUS:");

        cbStatusConta.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        cbStatusConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO" }));

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel6.setText("DESCRIÇÃO:");

        tbxDescricao.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxIDFornecedor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxNomeFornecedor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxNomeConta, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbStatusConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxDescricao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tbxIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(tbxNomeConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tbxIDFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cbStatusConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tbxNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(tbxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabela.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarContasVinculadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarContasVinculadasActionPerformed
        this.pesquisarContas();
    }//GEN-LAST:event_btnPesquisarContasVinculadasActionPerformed

    private void btnPesquisarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFornecedorActionPerformed
        fornecedor_conta = true;
        this.controller.pesquisarFornecedores();
    }//GEN-LAST:event_btnPesquisarFornecedorActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        this.controller.selecionarDados();
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
       this.controller.LimparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        this.controller.cadastro();
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnNovo;
    public static javax.swing.JButton btnPesquisarContasVinculadas;
    public static javax.swing.JButton btnPesquisarFornecedor;
    public static javax.swing.JButton btnSalvar;
    public static javax.swing.JComboBox<String> cbStatusConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    public static com.toedter.calendar.JCalendar jcDataCadastro;
    public static javax.swing.JTable tabela;
    public static javax.swing.JTextField tbxDescricao;
    public static javax.swing.JTextField tbxIDFornecedor;
    public static javax.swing.JTextField tbxIdConta;
    public static javax.swing.JTextField tbxNomeConta;
    public static javax.swing.JTextField tbxNomeFornecedor;
    // End of variables declaration//GEN-END:variables
public void pesquisarContas() {
        fornecedor_conta = false;
        this.controller.pesquisarDados();
    }
}
