/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuarioCtr;
import java.awt.Color;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import org.mindrot.jbcrypt.BCrypt;
import util.ActionButton;
import util.ActionCellEditor;
import util.ActionCellRenderer;
import util.ButtonEditor;
import util.ButtonRenderer;
import util.DynamicButtonsEditor;
import util.DynamicButtonsRenderer;
import DAO.ModelDAO;
import util.TableUtil;

/**
 *
 * @author RODOLFO
 */
public class DashboardTeste extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardTeste.class.getName());

    /**
     * Creates new form Dashboard
     */
    public DashboardTeste() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("jButton2");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*UsuarioCtr controller = new UsuarioCtr();
        List<Document> resultado = controller.LogarSistema("");

// 1. model com colunas fixas
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nome", "Email", "Ações"}, 0);

// 2. preencher dados
        for (Document doc : resultado) {

            model.addRow(new Object[]{
                doc.getObjectId("_id").toString(),
                doc.getString("nome_usuario"),
                doc.getString("email_usuario"),
                "" // coluna ações vazia
            });
        }

// 3. aplicar model na tabela
        jTable1.setModel(model);

        List<ActionButton> actions = List.of(
                new ActionButton("", "/imagens/button_icons/pequeno_16/lapis.png",
                        new Color(238, 238, 238),
                        new Color(41, 128, 185),
                        (id, t) -> System.out.println("Editar " + id)
                ),
                new ActionButton("", "/imagens/button_icons/pequeno_16/trash.png",
                        new Color(238, 238, 238),
                        new Color(192, 57, 43),
                        (id, t) -> System.out.println("Excluir " + id)
                )
        );

        jTable1.getColumn("Ações").setCellRenderer(new ActionCellRenderer(actions));
        jTable1.getColumn("Ações").setCellEditor(new ActionCellEditor(actions, jTable1));

        //List<ActionButton> botoes = Arrays.asList(
        //       new ActionButton("editar", "/imagens/button_icons/login.png", new Color(244, 67, 54),  new Color(211, 47, 47), (id, table) -> {
        //          System.out.println("editar: " + id);
        //    }),
        //  new ActionButton("excluir", "/imagens/button_icons/login.png",new Color(244, 67, 54),  new Color(211, 47, 47), (id, table) -> {
        //    System.out.println("excluir: " + id);
        // })
        //);
// aplica renderer/editor
        //jTable1.getColumn("Ações").setCellRenderer(new DynamicButtonsRenderer(botoes));
        //jTable1.getColumn("Ações").setCellEditor(new DynamicButtonsEditor(botoes));
// ajuste visual
        jTable1.setRowHeight(40);
        jTable1.getColumn("Ações").setPreferredWidth(120);*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //int linha = jTable1.getSelectedRow();

        //String id = jTable1.getValueAt(linha, 0).toString();
        //System.out.println("ID selecionado: " + id);
        //String senha = "Crydo879.";
        //qString hash = "$2y$10$cQOv8gSOcV..EKGvhiJs/uIeV37Y/ycPolQJbtbwQuPmKVFRgsFPW";
        // normaliza bcrypt PHP -> Java
        //hash = hash.replaceFirst("\\$2y\\$", "\\$2a\\$");
        // valida
        //boolean ok = BCrypt.checkpw(senha, hash);
        //System.out.println(ok ? "ok" : "erro");
        UsuarioCtr controller = new UsuarioCtr();
        controller.Teste();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardTeste().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
