package view;

import view.inferna_frame.JIFConta;
import model.Empresa;
import model.Usuarios;
import model.Sistema;
import controller.forms.JFDashboardCtr;
import util.Mensagens;
import view.inferna_frame.JIFClientesFornecedores;
import view.inferna_frame.JIFContaFornecedor;
import view.inferna_frame.JIFContasPagarReceber;

/**
 *
 * @author RODOLFO
 */
public class JFDashboard extends javax.swing.JFrame {

    public Empresa empresa;
    public Usuarios usuario;
    public Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFDashboard.class.getName());
    private JFDashboardCtr dashboardController;

    /**
     * Creates new form JFDashboard
     */
    public JFDashboard() {
        initComponents();
        
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        
        this.empresa = new Empresa();
        this.usuario = new Usuarios();
        this.sistema = new Sistema();
        
        this.dashboardController = new JFDashboardCtr();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        lNomeUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lVersaoSistema = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lDataEHora = new javax.swing.JLabel();
        jdpDashboard = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmContasPagarReceber = new javax.swing.JMenu();
        jmContasBancarias = new javax.swing.JMenuItem();
        jmClientesFornecedores = new javax.swing.JMenuItem();
        jmVincularContasFornecedores = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle Financeiro");

        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel1.setText(" Usuário Logado:  ");
        jToolBar1.add(jLabel1);

        lNomeUsuario.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        lNomeUsuario.setText("NOME_USUARIO_LOGADO");
        jToolBar1.add(lNomeUsuario);

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel3.setText("  Versão do Sistema:  ");
        jToolBar1.add(jLabel3);

        lVersaoSistema.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        lVersaoSistema.setText("VERSAO_SISTEMA");
        jToolBar1.add(lVersaoSistema);

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel5.setText("  Data e Hora:  ");
        jToolBar1.add(jLabel5);

        lDataEHora.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        lDataEHora.setText("HORAS");
        jToolBar1.add(lDataEHora);

        javax.swing.GroupLayout jdpDashboardLayout = new javax.swing.GroupLayout(jdpDashboard);
        jdpDashboard.setLayout(jdpDashboardLayout);
        jdpDashboardLayout.setHorizontalGroup(
            jdpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        jdpDashboardLayout.setVerticalGroup(
            jdpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        jmContasPagarReceber.setText("Cadastros");
        jmContasPagarReceber.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jmContasBancarias.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jmContasBancarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/contas_bancarias.png"))); // NOI18N
        jmContasBancarias.setText("Contas Bancárias");
        jmContasBancarias.setToolTipText("");
        jmContasBancarias.addActionListener(this::jmContasBancariasActionPerformed);
        jmContasPagarReceber.add(jmContasBancarias);

        jmClientesFornecedores.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jmClientesFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/clients.png"))); // NOI18N
        jmClientesFornecedores.setText("Clientes/Fornecedores");
        jmClientesFornecedores.setToolTipText("Clientes/Fornecedores");
        jmClientesFornecedores.addActionListener(this::jmClientesFornecedoresActionPerformed);
        jmContasPagarReceber.add(jmClientesFornecedores);

        jmVincularContasFornecedores.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jmVincularContasFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/fornecedor.png"))); // NOI18N
        jmVincularContasFornecedores.setText("Vincular Conta / Fornecedor");
        jmVincularContasFornecedores.setToolTipText("VINCULAR CONTA AO FORNECEDOR");
        jmVincularContasFornecedores.addActionListener(this::jmVincularContasFornecedoresActionPerformed);
        jmContasPagarReceber.add(jmVincularContasFornecedores);

        jMenuItem1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_icons/pequeno_16/contas.png"))); // NOI18N
        jMenuItem1.setText("Contas Pagar/Receber");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jmContasPagarReceber.add(jMenuItem1);

        jMenuBar1.add(jmContasPagarReceber);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jdpDashboard)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jdpDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmContasBancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmContasBancariasActionPerformed
        try{
        JIFConta contaBancarias = new JIFConta();
        jdpDashboard.add(contaBancarias);
        JIFConta.empresa = this.empresa;
        contaBancarias.pesquisarContas();
        contaBancarias.setMaximum(true);
        contaBancarias.setVisible(true);
        }catch(Exception ex){
            Mensagens.ErroException(ex);
        }
    }//GEN-LAST:event_jmContasBancariasActionPerformed

    private void jmClientesFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClientesFornecedoresActionPerformed
        try{
            JIFClientesFornecedores clientesFornecedores = new JIFClientesFornecedores();
        jdpDashboard.add(clientesFornecedores);
        JIFClientesFornecedores.empresa = this.empresa;
        clientesFornecedores.pesquisar_conta();
        clientesFornecedores.setMaximum(true);
        clientesFornecedores.setVisible(true);
        }catch(Exception ex){
            Mensagens.ErroException(ex);
        }
    }//GEN-LAST:event_jmClientesFornecedoresActionPerformed

    private void jmVincularContasFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVincularContasFornecedoresActionPerformed
        try{
        JIFContaFornecedor contaFornecedor = new JIFContaFornecedor();
        jdpDashboard.add(contaFornecedor);
        JIFContaFornecedor.empresa = this.empresa;
        contaFornecedor.pesquisarContas();
        contaFornecedor.setMaximum(true);
        contaFornecedor.setVisible(true);
        }catch(Exception ex){
            Mensagens.ErroException(ex);
        }
    }//GEN-LAST:event_jmVincularContasFornecedoresActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try{
            JIFContasPagarReceber contasPagarReceber = new JIFContasPagarReceber();
            jdpDashboard.add(contasPagarReceber);
            JIFContasPagarReceber.empresa = this.empresa;
            contasPagarReceber.LoadFormulario();
            contasPagarReceber.setMaximum(true);
            contasPagarReceber.setVisible(true);
        }catch(Exception ex){
            Mensagens.ErroException(ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JDesktopPane jdpDashboard;
    public static javax.swing.JMenuItem jmClientesFornecedores;
    public static javax.swing.JMenuItem jmContasBancarias;
    public static javax.swing.JMenu jmContasPagarReceber;
    public static javax.swing.JMenuItem jmVincularContasFornecedores;
    public static javax.swing.JLabel lDataEHora;
    public static javax.swing.JLabel lNomeUsuario;
    public static javax.swing.JLabel lVersaoSistema;
    // End of variables declaration//GEN-END:variables
public void iniciarSistema() {
        this.dashboardController.iniciarRelogio(lDataEHora);
        lNomeUsuario.setText(this.usuario.getLogin_usuario());
        this.sistema = this.dashboardController.getDadosSistema(this.empresa);
    }
}
